SELECT P.CODE AS PRIMARY_CODE, P.DESCRIPTION AS PRIMARY_DESC, NULL AS SECONDARY_CODE, NULL AS SECONDARY_DESC
FROM  ALOHA.V_LEAVE_CODES P
UNION
SELECT P.CODE AS PRIMARY_CODE, P.DESCRIPTION AS PRIMARY_DESC, S.CODE AS SECONDARY_CODE, S.DESCRIPTION AS SECONDARY_DESC
FROM  ALOHA.V_LEAVE_CODES P, ALOHA.V_SECONDARY_LEAVE_CODES S
WHERE S.PRIMARY_CODE = P.CODE
ORDER BY PRIMARY_CODE, SECONDARY_CODE NULLS FIRST